export const ROLES = {
  SUPER_ADMIN: 'Super Admin',
  HOD_PROCUREMENT: 'HOD Procurement',
  ASSISTANT_PROCUREMENT: 'Assistant Procurement',
  STORE_MANAGER: 'Store Manager',
  STOREKEEPER: 'Storekeeper',
  INVENTORY_OFFICER: 'Inventory Officer',
  COORDINATOR: 'Coordinator',
  HOD_SALES: 'HOD Sales',
  HOD_FINANCE: 'HOD Finance',
  FINANCE: 'Finance',
  ASSISTANT_FINANCE: 'Assistant Finance',
  FINANCE_OFFICER: 'Finance Officer',
  HOD_LOGISTICS: 'HOD Logistics',
  LOGISTICS_OFFICER: 'Logistics Officer',
  DRIVER: 'Driver',
  PRODUCTION_MANAGER: 'Production Manager',
  PRODUCTION_SUPERVISOR: 'Production Supervisor',
  MACHINE_OPERATOR: 'Machine Operator',
  HR_OFFICER: 'HR Officer',
  SALES_OFFICER: 'Sales Officer',
  GENERAL_MANAGER: 'General Manager',
  INTERNAL_AUDITOR: 'Internal Auditor',
  SAFETY_OFFICER: 'Safety Officer',
} as const;
