import { NavItem, NavSection } from '../models/navigation.models';

export const NAV_ITEMS: NavItem[] = [
  { labelKey: 'nav.dashboard', route: '/dashboard', icon: 'dashboard', module: null, section: 'main' },
  { labelKey: 'nav.inventory.title', route: '/inventory/dashboard', icon: 'inventory',
    module: 'inventory',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.inventory.dashboard', route: '/inventory/dashboard', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.items', route: '/inventory/items', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.categories', route: '/inventory/categories', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.warehouses', route: '/inventory/warehouses', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.stock', route: '/inventory/stock', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.grn', route: '/inventory/grn', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.gin', route: '/inventory/gin', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.transfers', route: '/inventory/transfers', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.reservations', route: '/inventory/reservations', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.movements', route: '/inventory/movements', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.adjustments', route: '/inventory/adjustments', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.my_requests', route: '/inventory/my-requests', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.department_approvals', route: '/inventory/department-approvals', module: 'inventory', action: 'approve' },
      { labelKey: 'nav.inventory.internal_issue', route: '/inventory/internal-issue', module: 'inventory', action: 'create' },
      { labelKey: 'nav.inventory.department_requests', route: '/inventory/department-requests', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.stock_take', route: '/inventory/stock-take', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.purchase_requisitions', route: '/inventory/purchase-requisitions', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.manufacturing', route: '/inventory/manufacturing', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.valuation', route: '/inventory/valuation', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.alerts', route: '/inventory/alerts', module: 'inventory', action: 'read' },
      { labelKey: 'nav.inventory.reports', route: '/inventory/reports', module: 'inventory', action: 'read' },
    ],
  },
  { labelKey: 'nav.procurement.title', route: '/procurement/dashboard', icon: 'procurement',
    module: 'procurement',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.procurement.dashboard', route: '/procurement/dashboard', module: 'procurement', action: 'read' },
      { labelKey: 'nav.procurement.suppliers', route: '/procurement/suppliers', module: 'procurement', action: 'read' },
      { labelKey: 'nav.procurement.requisitions', route: '/procurement/requisitions', module: 'procurement', action: 'read' },
      { labelKey: 'nav.procurement.rfq', route: '/procurement/rfq', module: 'procurement', action: 'read' },
      { labelKey: 'nav.procurement.quotations', route: '/procurement/quotations', module: 'procurement', action: 'read' },
      { labelKey: 'nav.procurement.purchase_orders', route: '/procurement/purchase-orders', module: 'procurement', action: 'read' },
      { labelKey: 'nav.procurement.grn', route: '/procurement/grn', module: 'procurement', action: 'read' },
      { labelKey: 'nav.procurement.supplier_invoices', route: '/procurement/supplier-invoices', module: 'procurement', action: 'read' },
    ],
  },
  { labelKey: 'nav.sales.title', route: '/sales/dashboard', icon: 'sales',
    module: 'sales',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.sales.dashboard', route: '/sales/dashboard', module: 'sales', action: 'read' },
      { labelKey: 'nav.sales.customers', route: '/sales/customers', module: 'sales', action: 'read' },
      { labelKey: 'nav.sales.quotations', route: '/sales/quotations', module: 'sales', action: 'read' },
      { labelKey: 'nav.sales.orders', route: '/sales/orders', module: 'sales', action: 'read' },
      { labelKey: 'nav.sales.invoices', route: '/sales/invoices', module: 'sales', action: 'read' },
      { labelKey: 'nav.sales.payments', route: '/sales/payments', module: 'sales', action: 'read' },
      { labelKey: 'nav.sales.credit_notes', route: '/sales/credit-notes', module: 'sales', action: 'read' },
    ],
  },
  { labelKey: 'nav.logistics.title', route: '/logistics/dashboard', icon: 'logistics',
    module: 'logistics',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.logistics.dashboard', route: '/logistics/dashboard', module: 'logistics', action: 'read' },
      { labelKey: 'nav.logistics.vehicles', route: '/logistics/vehicles', module: 'logistics', action: 'read' },
      { labelKey: 'nav.logistics.drivers', route: '/logistics/drivers', module: 'logistics', action: 'read' },
      { labelKey: 'nav.logistics.deliveries', route: '/logistics/deliveries', module: 'logistics', action: 'read' },
      { labelKey: 'nav.logistics.sales_queue', route: '/logistics/sales-queue', module: 'logistics', action: 'read' },
      { labelKey: 'nav.logistics.delivery_notes', route: '/logistics/delivery-notes', module: 'logistics', action: 'read' },
      { labelKey: 'nav.logistics.maintenance', route: '/logistics/maintenance', module: 'logistics', action: 'read' },
      { labelKey: 'nav.logistics.fuel', route: '/logistics/fuel', module: 'logistics', action: 'read' },
    ],
  },
  { labelKey: 'nav.driver_portal.title', route: '/driver-portal/dashboard', icon: 'driver',
    module: 'driver_portal',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.driver_portal.dashboard', route: '/driver-portal/dashboard', module: 'driver_portal', action: 'read' },
      { labelKey: 'nav.driver_portal.trips', route: '/driver-portal/trips', module: 'driver_portal', action: 'read' },
      { labelKey: 'nav.driver_portal.history', route: '/driver-portal/history', module: 'driver_portal', action: 'read' },
      { labelKey: 'nav.driver_portal.vehicle', route: '/driver-portal/vehicle', module: 'driver_portal', action: 'read' },
      { labelKey: 'nav.driver_portal.profile', route: '/driver-portal/profile', module: 'driver_portal', action: 'read' },
    ],
  },
  { labelKey: 'nav.production.title', route: '/production/dashboard', icon: 'production',
    module: 'production',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.production.dashboard', route: '/production/dashboard', module: 'production', action: 'read' },
      { labelKey: 'nav.production.operator', route: '/production/operator', module: 'production', action: 'read' },
      { labelKey: 'nav.production.products', route: '/production/products', module: 'production', action: 'read' },
      { labelKey: 'nav.production.bom', route: '/production/bom', module: 'production', action: 'read' },
      { labelKey: 'nav.production.work_orders', route: '/production/work-orders', module: 'production', action: 'read' },
      { labelKey: 'nav.production.output', route: '/production/output', module: 'production', action: 'read' },
      { labelKey: 'nav.production.machines', route: '/production/machines', module: 'production', action: 'read' },
      { labelKey: 'nav.production.machine_usage', route: '/production/machine-usage', module: 'production', action: 'read' },
    ],
  },
  { labelKey: 'nav.finance.title', route: '/finance/dashboard', icon: 'finance',
    module: 'finance',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.finance.dashboard', route: '/finance/dashboard', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.accounts', route: '/finance/accounts', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.journal_entries', route: '/finance/journal-entries', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.receivables', route: '/finance/receivables', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.payables', route: '/finance/payables', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.payroll_approvals', route: '/finance/payroll-approvals', module: 'finance', action: 'approve' },
      { labelKey: 'nav.finance.bank_accounts', route: '/finance/bank-accounts', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.reconciliation', route: '/finance/reconciliation', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.budgets', route: '/finance/budgets', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.tax', route: '/finance/tax', module: 'finance', action: 'read' },
      { labelKey: 'nav.finance.reports', route: '/finance/reports', module: 'finance', action: 'read' },
    ],
  },
  { labelKey: 'nav.hr.title', route: '/hr/dashboard', icon: 'hr',
    module: 'hr',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.hr.dashboard', route: '/hr/dashboard', module: 'hr', action: 'read' },
      { labelKey: 'nav.hr.employees', route: '/hr/employees', module: 'hr', action: 'read' },
      { labelKey: 'nav.hr.attendance', route: '/hr/attendance', module: 'hr', action: 'read' },
      { labelKey: 'nav.hr.leave', route: '/hr/leave', module: 'hr', action: 'read' },
      { labelKey: 'nav.hr.payroll', route: '/hr/payroll', module: 'hr', action: 'read' },
      { labelKey: 'nav.hr.payslips', route: '/hr/payslips', module: 'hr', action: 'read' },
      { labelKey: 'nav.hr.appraisals', route: '/hr/appraisals', module: 'hr', action: 'read' },
      { labelKey: 'nav.hr.disciplinary', route: '/hr/disciplinary', module: 'hr', action: 'read' },
      { labelKey: 'nav.hr.admin', route: '/hr/admin', module: 'hr', action: 'read' },
    ],
  },
  { labelKey: 'nav.safety.title', route: '/safety/dashboard', icon: 'safety',
    module: 'safety',
    action: 'read',
    section: 'modules',
    children: [
      { labelKey: 'nav.safety.dashboard', route: '/safety/dashboard', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.incidents', route: '/safety/incidents', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.inspections', route: '/safety/inspections', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.ppe', route: '/safety/ppe', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.permits', route: '/safety/permits', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.training', route: '/safety/training', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.reports', route: '/safety/reports', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.dashboard', route: '/safety/security/dashboard', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.visitors', route: '/safety/security/visitors', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.vehicles', route: '/safety/security/vehicles', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.inter_location', route: '/safety/security/inter-location', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.personnel', route: '/safety/security/personnel', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.shifts', route: '/safety/security/shifts', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.access', route: '/safety/security/access', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.incidents', route: '/safety/security/incidents', module: 'safety', action: 'read' },
      { labelKey: 'nav.safety.security.reports', route: '/safety/security/reports', module: 'safety', action: 'read' },
    ],
  },
  { labelKey: 'nav.messaging', route: '/messaging', icon: 'messages',
    module: 'messaging',
    action: 'read',
    badgeKey: 'messages',
    section: 'system',
  },
  { labelKey: 'nav.email', route: '/email', icon: 'email',
    module: 'email',
    action: 'read',
    badgeKey: 'email',
    section: 'system',
  },
  { labelKey: 'nav.settings', route: '/settings', icon: 'settings',
    module: 'settings',
    action: 'read',
    section: 'system',
  },
];

export const NAV_SECTION_LABELS: Record<Exclude<NavSection, 'main'>, string> = {
  modules: 'nav.sections.modules',
  system: 'nav.sections.system',
};
