import { ChangeDetectionStrategy, Component, computed, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { finalize } from 'rxjs/operators';

import {
  FinanceApprovalQueue,
  FinanceApprovalQueueItem,
  FinanceDocumentApprovalStatus,
  FinanceInvoiceDetail,
} from '../../../../core/models/finance.model';
import { Invoice } from '../../../../core/models/sales.model';
import { SupplierInvoice } from '../../../../core/models/procurement.model';
import { AuthService } from '../../../../core/services/auth.service';
import { FinanceService } from '../../../../core/services/finance.service';
import { NotificationService } from '../../../../core/services/notification.service';
import { getApiErrorMessage } from '../../../../core/utils/api.util';
import { formatCurrency, formatDateTime } from '../../../../core/utils/format.util';
import { EmptyStateComponent } from '../../../../shared/components/empty-state/empty-state.component';
import { ModalComponent } from '../../../../shared/components/modal/modal.component';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { StatusBadgeComponent } from '../../../../shared/components/status-badge/status-badge.component';
import { TableSkeletonComponent } from '../../../../shared/components/table-skeleton/table-skeleton.component';
import { FinanceNavComponent } from '../../components/finance-nav/finance-nav.component';
import { canFinanceHodApprove } from '../../utils/finance-permissions.util';
import { FinanceInvoiceDetailModalComponent } from './finance-invoice-detail-modal.component';

type DocTab = 'received' | 'sent';
type CompanyTab = 'SUPPLY' | 'STEIN';
type StatusTab = 'pending' | 'approved' | 'sent';

@Component({
  selector: 'app-finance-approval-queue',
  imports: [
    FormsModule,
    PageHeaderComponent,
    FinanceNavComponent,
    EmptyStateComponent,
    TableSkeletonComponent,
    StatusBadgeComponent,
    ModalComponent,
    FinanceInvoiceDetailModalComponent,
  ],
  templateUrl: './finance-approval-queue.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FinanceApprovalQueueComponent implements OnInit {
  private readonly finance = inject(FinanceService);
  private readonly auth = inject(AuthService);
  private readonly notification = inject(NotificationService);
  private readonly route = inject(ActivatedRoute);

  readonly queue = signal<FinanceApprovalQueue | null>(null);
  readonly loading = signal(true);
  readonly acting = signal(false);
  readonly docTab = signal<DocTab>('sent');
  readonly companyTab = signal<CompanyTab>('SUPPLY');
  readonly statusTab = signal<StatusTab>('pending');
  readonly showReject = signal(false);
  readonly rejectReason = signal('');
  readonly rejecting = signal<FinanceApprovalQueueItem | null>(null);
  readonly showDetail = signal(false);
  readonly detailLoading = signal(false);
  readonly detail = signal<FinanceInvoiceDetail<SupplierInvoice | Invoice> | null>(null);
  readonly detailItem = signal<FinanceApprovalQueueItem | null>(null);

  readonly formatCurrency = formatCurrency;
  readonly formatDateTime = formatDateTime;
  readonly canApprove = () => canFinanceHodApprove(this.auth);

  readonly items = computed(() => {
    const q = this.queue();
    if (!q) return [];
    const bucket =
      this.docTab() === 'received' ? q.invoice_received : q.invoice_sent;
    return bucket[this.companyTab()] ?? [];
  });

  readonly pageSubtitle = computed(() => {
    if (this.docTab() === 'sent') {
      switch (this.statusTab()) {
        case 'pending':
          return 'Sales invoices generated by Finance — awaiting issue to the customer';
        case 'approved':
          return 'Issued sales invoices — ready to email to the customer';
        case 'sent':
          return 'Sales invoices emailed to customers';
      }
    }
    return this.statusTab() === 'approved'
      ? 'Supplier invoices approved by Finance HOD'
      : 'Supplier invoices awaiting Finance HOD document approval';
  });

  readonly showSalesLifecycleTabs = computed(() => this.docTab() === 'sent');

  ngOnInit(): void {
    const tab = this.route.snapshot.queryParamMap.get('tab');
    const company = this.route.snapshot.queryParamMap.get('company');
    const status = this.route.snapshot.queryParamMap.get('status');
    if (tab === 'received') this.docTab.set('received');
    if (tab === 'sent') this.docTab.set('sent');
    if (company === 'STEIN' || company === 'SUPPLY') {
      this.companyTab.set(company);
    }
    if (status === 'approved' || status === 'sent' || status === 'pending') {
      this.statusTab.set(status);
    }
    if (this.docTab() === 'received' && this.statusTab() === 'sent') {
      this.statusTab.set('pending');
    }
    this.load();
  }

  load(): void {
    this.loading.set(true);
    this.finance
      .getApprovalQueue(this.statusTab())
      .pipe(finalize(() => this.loading.set(false)))
      .subscribe({
        next: (data) => this.queue.set(data),
        error: (e) => this.notification.error(getApiErrorMessage(e)),
      });
  }

  setDocTab(tab: DocTab): void {
    this.docTab.set(tab);
    if (tab === 'received' && this.statusTab() === 'sent') {
      this.statusTab.set('pending');
    }
    this.load();
  }

  setStatusTab(tab: StatusTab): void {
    this.statusTab.set(tab);
    this.load();
  }

  statusCount(tab: StatusTab): number | undefined {
    const q = this.queue();
    if (!q) return undefined;
    if (this.docTab() === 'sent') {
      if (tab === 'pending') return q.counts.pending_sent;
      if (tab === 'approved') return q.counts.approved_sent;
      return q.counts.sent_to_customer;
    }
    if (tab === 'pending') return q.counts.pending_received;
    return q.counts.approved_received;
  }

  openDetail(item: FinanceApprovalQueueItem): void {
    this.detailItem.set(item);
    this.showDetail.set(true);
    this.detailLoading.set(true);
    this.detail.set(null);
    const onSuccess = (data: FinanceInvoiceDetail<SupplierInvoice | Invoice>) => {
      this.detail.set(data);
    };
    const onError = (e: unknown) => {
      this.notification.error(getApiErrorMessage(e));
      this.showDetail.set(false);
    };
    if (item.doc_type === 'invoice_received') {
      this.finance
        .getInvoiceReceivedDetail(item.id)
        .pipe(finalize(() => this.detailLoading.set(false)))
        .subscribe({ next: onSuccess, error: onError });
    } else {
      this.finance
        .getInvoiceSentDetail(item.id)
        .pipe(finalize(() => this.detailLoading.set(false)))
        .subscribe({ next: onSuccess, error: onError });
    }
  }

  closeDetail(): void {
    this.showDetail.set(false);
    this.detail.set(null);
    this.detailItem.set(null);
  }

  approveFromDetail(): void {
    const item = this.detailItem();
    if (!item) return;
    this.approve(item);
  }

  rejectFromDetail(): void {
    const item = this.detailItem();
    if (!item) return;
    this.closeDetail();
    this.openReject(item);
  }

  approvalLabel(
    status: FinanceDocumentApprovalStatus | undefined,
    item?: FinanceApprovalQueueItem,
  ): string {
    if (item?.doc_type === 'invoice_sent') {
      switch (status) {
        case 'PENDING_ISSUE':
          return 'Awaiting Issue';
        case 'ISSUED':
          return 'Issued';
        case 'SENT_TO_CUSTOMER':
          return 'Sent to Customer';
        default:
          return 'Sales Invoice';
      }
    }
    switch (status) {
      case 'PENDING_FINANCE_APPROVAL':
        return 'Pending Finance';
      case 'APPROVED':
        return 'Finance Approved';
      case 'REJECTED':
        return 'Finance Rejected';
      default:
        return 'Not Submitted';
    }
  }

  submittedColumnLabel(): string {
    if (this.docTab() === 'sent') {
      if (this.statusTab() === 'sent') return 'Sent';
      if (this.statusTab() === 'approved') return 'Issued';
      return 'Created';
    }
    return this.statusTab() === 'approved' ? 'Approved' : 'Submitted';
  }

  submittedColumnValue(item: FinanceApprovalQueueItem): { primary: string; secondary: string } {
    if (this.docTab() === 'sent') {
      if (this.statusTab() === 'sent') {
        return {
          primary: item.invoice_sent_at ? formatDateTime(item.invoice_sent_at) : '—',
          secondary: item.approved_by_name ?? 'Finance',
        };
      }
      if (this.statusTab() === 'approved') {
        return {
          primary: item.approved_by_name ?? 'Finance',
          secondary: item.approved_at ? formatDateTime(item.approved_at) : '—',
        };
      }
      return {
        primary: item.submitted_by_name ?? 'Finance',
        secondary: item.submitted_at ? formatDateTime(item.submitted_at) : '—',
      };
    }
    if (this.statusTab() === 'approved') {
      return {
        primary: item.approved_by_name ?? 'Historical',
        secondary: item.approved_at ? formatDateTime(item.approved_at) : '—',
      };
    }
    return {
      primary: item.submitted_by_name ?? '—',
      secondary: item.submitted_at ? formatDateTime(item.submitted_at) : '—',
    };
  }

  emptyStateTitle(): string {
    if (this.docTab() === 'sent') {
      if (this.statusTab() === 'pending') return 'No Draft Sales Invoices';
      if (this.statusTab() === 'approved') return 'No Issued Sales Invoices';
      return 'No Invoices Sent to Customers';
    }
    return this.statusTab() === 'approved' ? 'Approved Supplier Invoices' : 'Pending Supplier Approvals';
  }

  emptyStateMessage(): string {
    if (this.docTab() === 'sent') {
      if (this.statusTab() === 'pending') {
        return 'Generate a sales invoice from the sales order — it will appear here until Finance issues it.';
      }
      if (this.statusTab() === 'approved') {
        return 'Issue a draft invoice first, then it will appear here before emailing the customer.';
      }
      return 'Use Send to Customer on an issued invoice — it will appear here after the email is sent.';
    }
    return this.statusTab() === 'approved'
      ? 'No finance-approved supplier invoices in this company bucket yet.'
      : 'No supplier invoices awaiting Finance HOD approval in this bucket.';
  }

  approve(item: FinanceApprovalQueueItem): void {
    if (!this.canApprove() || item.doc_type !== 'invoice_received') return;
    this.acting.set(true);
    this.finance
      .approveInvoiceReceived(item.id)
      .pipe(finalize(() => this.acting.set(false)))
      .subscribe({
        next: (res) => {
          this.notification.success(res.message);
          this.closeDetail();
          this.load();
        },
        error: (e) => this.notification.error(getApiErrorMessage(e)),
      });
  }

  openReject(item: FinanceApprovalQueueItem): void {
    this.rejecting.set(item);
    this.rejectReason.set('');
    this.showReject.set(true);
  }

  confirmReject(): void {
    const item = this.rejecting();
    if (!item || item.doc_type !== 'invoice_received') return;
    this.acting.set(true);
    const reason = this.rejectReason().trim();
    this.finance
      .rejectInvoiceReceived(item.id, reason)
      .pipe(finalize(() => this.acting.set(false)))
      .subscribe({
        next: (res) => {
          this.showReject.set(false);
          this.rejecting.set(null);
          this.notification.success(res.message);
          this.load();
        },
        error: (e) => this.notification.error(getApiErrorMessage(e)),
      });
  }
}
